### PR TITLE
accomodate folder structure to that of project-generator, see #1

### PR DESCRIPTION
**Pull request by jgvictores**
Accomodate folder structure to that of project-generator. Allows better FIND_PACKAGE, as well as uninstall targets and much much more!

### CODE REVIEW

**Review by munozyanez — CHANGES_REQUESTED** [review]
Please keep folder structure for submodule users

**Review by munozyanez — APPROVED** [review]

**Review by munozyanez — CHANGES_REQUESTED** [review]
You can change cmake folder, but no need to change the src folder.
Keep old structure for sources.

**Comment by jgvictores** [comment]
Recovered the original src dir, and did some cleanup:
https://github.com/roboticslab-uc3m/gait/pull/3/commits

**Comment by jgvictores** [comment]
@munozyanez Could you please review changes?

**Comment by jgvictores** [comment]
@munozyanez Thanks!

**Comment by munozyanez** [comment]
Looks great now.

**Pull request merged**
